name: Deploy with Secrets

on:
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Authenticate with Google Cloud
        run: |
          echo "${{ secrets.GCP_SA_KEY }}" | base64 -d > gcp-key.json
          ls -l gcp-key.json
          cat gcp-key.json || true
          gcloud auth activate-service-account --key-file=gcp-key.json
          gcloud config set project ${{ secrets.PROJECT_ID }}


      - name: Make script executable
        run: chmod +x external/report-builder/deploy.sh

      - name: Run deploy script
        run: external/report-builder/deploy.sh
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
          CLIENT_EMAIL: ${{ secrets.CLIENT_EMAIL }}
          PROJECT: ${{ secrets.PROJECT_ID }}
          PRIVATE_KEY: $PRIVATE_KEY
