name: Deploy with Secrets 

on:
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Authenticate with Google Cloud
        run: |
          printf "%s" "${{ secrets.GCP_SA_KEY }}" > gcp-key.json
          gcloud auth activate-service-account --key-file=gcp-key.json
          gcloud config set project ${{ secrets.PROJECT_ID }}
            
      - name: modify PRIVATE_KEY newlines
        run: |
          echo -e "${{ secrets.PRIVATE_KEY }}" > private-key.json
          export PRIVATE_KEY=$(cat private-key.json)

      - name: Make script executable
        run: chmod +x ./deploy.sh

      - name: Run deploy script
        run: ./deploy.sh
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
          CLIENT_EMAIL: ${{ secrets.CLIENT_EMAIL }}
          PROJECT: ${{ secrets.PROJECT_ID }}
          PRIVATE_KEY: $PRIVATE_KEY
