name: Deploy with Secrets

on:
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Make script executable
        run: chmod +x ./external/report-builder/deploy.sh

      - name: Run Deploy Script
        run: ./external/report-builder/deploy.sh
        env:
            CLIENT_EMAIL: ${{ secrets.CLIENT_EMAIL }}
            PRIVATE_KEY: ${{ secrets.PRIVATE_KEY }}
            PROJECT: ${{ secrets.PROJECT }}  